[package]
name = "donotpublish/metaunios"
private = true
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Feather = "blinkybool/feather@0.2.1"
Sift = "csqrl/sift@0.0.4"
Roact = "roblox/roact@1.4.4"
Promise = "evaera/promise@4.0.0"
GoodSignal = "stravant/goodsignal@0.2.1"
Fusion = "elttob/fusion@0.2.0"
t = "osyrisrblx/t@3.0.0"